[package]
name = "uwufetch-port"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
displayz = "0.1.0"
regex = "1.10.5"
serde = "1.0.204"
share = "0.1.0"
sysinfo = "0.30.13"
uwuizer = "0.3.0"
whoami = "1.5.1"
winapi = "0.3.9"
winver = "1.0.0"
wmi = "0.13.3"
